# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
# Set one of you dependencies from github
r_github_packages: r-lib/testthat
# Set one of your dependencies from CRAN
r_packages:
 - dplyr
 - ggplot2
 - sqldf
 - stringr
 - covr
# set a Linux system dependency
apt_packages:
 - libxml2-dev
env:
 - CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"
script:
 - Rscript -e "library(testthat); testthat::test_dir('tests/testthat/')"
after_success:
  - Rscript -e 'library(covr); covr::codecov(token=CODECOV_TOKEN)'
