# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
# Set one of your dependencies from CRAN
r_packages:
 - dplyr
 - ggplot2
 - sqldf
 - stringr
 - testthat
 - covr
# set a Linux system dependency
apt_packages:
 - libxml2-dev
env:
 - CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"
script:
 - R CMD build helda_0.1.tar.gz
 - R CMD check --as-cran helda_0.1.tar.gz
after_success:
  - Rscript -e 'library(covr); covr::codecov(token=CODECOV_TOKEN)'
