# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
# Set one of your dependencies from CRAN
r_packages:
 - dplyr
 - ggplot2
 - sqldf
 - stringr
 - devtools
 - testthat
 - covr
# set a Linux system dependency
apt_packages:
 - libxml2-dev
env:
 - CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"
install:
- R -e 'library(devtools); devtools::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz
after_success:
  - Rscript -e 'library(covr); covr::codecov(token=CODECOV_TOKEN)'
