# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel
jobs:
  include:
    - os: linux
      dist: xenial
      r: oldrel
    - os: linux
      dist: xenial
      r: release
    - os: linux
      dist: xenial
      r: devel
    - os: linux
      dist: xenial
      r: bioc-devel
    - os: osx
      osx_image: xcode11
      r: oldrel
    - os: osx
      r: release
      osx_image: xcode11
services:
  - xvfb
# Set one of your dependencies from CRAN
r_packages:
 - dplyr
 - ggplot2
 - sqldf
 - stringr
 - testthat
 - covr
# set a Linux system dependency
before_install:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get update; fi
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get -y install libxml2-dev; fi
env:
 - CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"
install:
- R -e 'devtools::install_deps(dep = T)'
script:
 - R CMD build .
 - R CMD check --as-cran *.tar.gz
after_success:
  - Rscript -e 'library(covr); CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"; covr::codecov(coverage=covr::package_coverage(path="."), token=CODECOV_TOKEN)'
