comment: false
language: R
sudo: false
cache: packages
env:
- CODECOV_TOKEN="6073f04a-c72e-41e1-87a1-81a856f76aac"
after_success:
- Rscript -e 'covr::codecov(token=CODECOV_TOKEN)'

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
